services:
  sql:
    image: sqlserver-fts:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
        REPO_DISTRO_VERSION: ${REPO_DISTRO_VERSION}
        MSSQL_REPO_FLAVOR: ${MSSQL_REPO_FLAVOR}
        INSTALL_HA: ${INSTALL_HA}
        INSTALL_FTS: ${INSTALL_FTS}
